-- MySQL Script generated by MySQL Workbench
-- 06/30/16 20:50:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema students_ranking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema students_ranking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `students_ranking` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `students_ranking` ;

-- -----------------------------------------------------
-- Table `students_ranking`.`specialities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `students_ranking`.`specialities` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `students_ranking`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `students_ranking`.`classes` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `speciality_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_classes_specialities1_idx` (`speciality_id` ASC)  COMMENT '',
  CONSTRAINT `fk_classes_specialities1`
    FOREIGN KEY (`speciality_id`)
    REFERENCES `students_ranking`.`specialities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `students_ranking`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `students_ranking`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `class_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_groups_classes1_idx` (`class_id` ASC)  COMMENT '',
  CONSTRAINT `fk_groups_classes1`
    FOREIGN KEY (`class_id`)
    REFERENCES `students_ranking`.`classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `students_ranking`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `students_ranking`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(70) NOT NULL COMMENT '',
  `faculty_number` VARCHAR(20) NOT NULL COMMENT '',
  `group_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `faculty_number_UNIQUE` (`faculty_number` ASC)  COMMENT '',
  INDEX `fk_students_groups_idx` (`group_id` ASC)  COMMENT '',
  CONSTRAINT `fk_students_groups`
    FOREIGN KEY (`group_id`)
    REFERENCES `students_ranking`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `students_ranking`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `students_ranking`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `description` TEXT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `students_ranking`.`activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `students_ranking`.`activities` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `points` INT NOT NULL COMMENT '',
  `course_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_activities_courses1_idx` (`course_id` ASC)  COMMENT '',
  CONSTRAINT `fk_activities_courses1`
    FOREIGN KEY (`course_id`)
    REFERENCES `students_ranking`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `students_ranking`.`courses_specialities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `students_ranking`.`courses_specialities` (
  `course_id` INT NOT NULL COMMENT '',
  `speciality_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`course_id`, `speciality_id`)  COMMENT '',
  INDEX `fk_courses_has_specialities_specialities1_idx` (`speciality_id` ASC)  COMMENT '',
  INDEX `fk_courses_has_specialities_courses1_idx` (`course_id` ASC)  COMMENT '',
  CONSTRAINT `fk_courses_has_specialities_courses1`
    FOREIGN KEY (`course_id`)
    REFERENCES `students_ranking`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_has_specialities_specialities1`
    FOREIGN KEY (`speciality_id`)
    REFERENCES `students_ranking`.`specialities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `students_ranking`.`students_activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `students_ranking`.`students_activities` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `student_id` INT NOT NULL COMMENT '',
  `activity_id` INT NOT NULL COMMENT '',
  `datetime` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_students_has_activities_activities1_idx` (`activity_id` ASC)  COMMENT '',
  INDEX `fk_students_has_activities_students1_idx` (`student_id` ASC)  COMMENT '',
  CONSTRAINT `fk_students_has_activities_students1`
    FOREIGN KEY (`student_id`)
    REFERENCES `students_ranking`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_has_activities_activities1`
    FOREIGN KEY (`activity_id`)
    REFERENCES `students_ranking`.`activities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
